spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cellulant_db
    username: mmcs_dbm
    password: <9r0@q7iV3_1O>    
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        id:
          new_generator_mappings: false
          